"""Provenance marker for pipeline-generated SRT subtitles.

Uploader captions and the pipeline's own generated subtitles land at the
same path (``subtitles/<stem>.srt``), so nothing on disk distinguishes the
two provenances by default — a regen can mistake its own prior output for a
real caption. A generated SRT is marked with a sidecar file
(``subtitles/<stem>.srt.generated``) right after it's written; discovery
sites treat a marked SRT as "no caption" rather than adopting it. Sidecar,
not SRT content: SubRip has no comment syntax, and the marker must survive
tools that rewrite the ``.srt``'s body.
"""

from pathlib import Path

_MARKER_SUFFIX = ".generated"
_MARKER_CONTENT = "Generated by PiKaraoke's lyric-align stage; not an uploader caption.\n"


def _marker_for(srt_path: Path) -> Path:
    return srt_path.parent / (srt_path.name + _MARKER_SUFFIX)


def mark_generated(srt_path: Path) -> None:
    """Write the sidecar marker next to a just-written generated SRT."""
    _marker_for(srt_path).write_text(_MARKER_CONTENT, encoding="utf-8")


def is_generated(srt_path: Path) -> bool:
    """True if ``srt_path`` was written by the pipeline, not an uploader."""
    return _marker_for(srt_path).is_file()


def clear_generated_marker(srt_path: Path) -> None:
    """Remove a stale marker next to ``srt_path``; a no-op when none exists."""
    _marker_for(srt_path).unlink(missing_ok=True)
